//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TCondition
{
    public TCondition()
    {
        this.TPatientConditions = new HashSet<TPatientCondition>();
    }

    public int intConditionID { get; set; }
    public string strCondition { get; set; }
    public string strICD10Code { get; set; }
    public string strDescription { get; set; }

    public virtual ICollection<TPatientCondition> TPatientConditions { get; set; }
}

public partial class TPatientCondition
{
    public int intPatientID { get; set; }
    public int intConditionID { get; set; }
    public string dteDateDiagnosed { get; set; }

    public virtual TCondition TCondition { get; set; }
}
